apiVersion: v1
kind: Service
metadata:
  name: spring-springboot-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-springboot-app