apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skaffold-springboot
  template:
    metadata:
      labels:
        app: skaffold-springboot
    spec:
      containers:
        - name: skaffold-springboot
          image: skaffold-springboot
          ports:
            - containerPort: 8080
